task/WMAQA-13 Tests for unauthorized users
TACC/Core-Portal-E2E pull request #10
Opened 2023-08-16 21:27 UTC by shayanaijaz

Added couple of tests for unauthorized user. Added a new project to playwright config where the tests in the unauthorized-user folder are run without the authentication step being run

2023-08-28 20:52 UTC, SilversunKSauri requested changes

2023-08-28 20:52 UTC, SilversunKSauri commented on tests/unauthorized-user/unauthorized-user.spec.js
> +    await expect(heading).toHaveText('Tapis Login - Tenant portals');
I think with the updated Tapis login page that this isn't correct anymore?  I just ran this test and playwright is reporting it received an empty string instead of this text.

2023-08-28 20:53 UTC, shayanaijaz commented on tests/unauthorized-user/unauthorized-user.spec.js
> +    await expect(heading).toHaveText('Tapis Login - Tenant portals');
Yeah there could be an issue here, I'll update this

2023-08-31 17:45 UTC, shayanaijaz commented on tests/unauthorized-user/unauthorized-user.spec.js
> +    await expect(heading).toHaveText('Tapis Login - Tenant portals');
@SilversunKSauri this should be updated now

2023-09-05 18:33 UTC, SilversunKSauri approved these changes
LGTM, works after the latest changes

2023-09-05 18:34 UTC, merged