task/WMAQA-38 - Refactor tests to be portal agnostic
TACC/Core-Portal-E2E pull request #22
Opened 2024-01-22 17:05 UTC by fnets

Tests now work with Frontera Portal.

2024-01-29 16:56 UTC, shayanaijaz requested changes
In prod frontera, I have one test failing which is [unauthorized-user.spec.js](https://github.com/TACC/Core-Portal-E2E/blob/main/tests/unauthorized-user/unauthorized-user.spec.js). It is failing because that test also checks Public Data and there isn't a skip condition added in there. 

I also ran the tests on pprd frontera (which we should also test and add support for in this PR) and that one seems to be failing on the Onboarding Admin tests since the user does not have admin access there. We should probably add a condition to skip the Onboarding Admin tests if the user doesn't have admin. 

One way we can check for admin status is by visiting the django core admin site (e.g [frontera-portal.tacc.utexas.edu/core/admin](frontera-portal.tacc.utexas.edu/core/admin)). If the user has admin access they should be able to view the Site Administration page. If they don't, then they are redirected to the login page and shown an error message. We can use this to determine admin status, and skip Onboarding Admin tests if they are shown the error message. Let me know what you think

2024-01-29 16:56 UTC, shayanaijaz commented on tests/publicData/publicData.spec.js
> +
There are other portals such as [3dem](https://3dem.org/) that also have Public Data access. Might need a different approach to filter out systems with Public Data

2024-01-29 20:51 UTC, fnets commented on tests/publicData/publicData.spec.js
> +
Good catch, it's always the portal you forget to check. I think I have a way around this, by checking Storage Systems for Public Data. But, that doesn't guarantee that there will be a CMS button available (MISE, for example).

2024-01-29 20:58 UTC, fnets commented
> In prod frontera, I have one test failing which is [unauthorized-user.spec.js](https://github.com/TACC/Core-Portal-E2E/blob/main/tests/unauthorized-user/unauthorized-user.spec.js). It is failing because that test also checks Public Data and there isn't a skip condition added in there.

Good catch! Don't know how I missed that.

>Pprd frontera (which we should also test and add support for in this PR) and that one seems to be failing on the Onboarding Admin tests since the user does not have admin access there. We should probably add a condition to skip the Onboarding Admin tests if the user doesn't have admin.

I think your suggested test is a good one, but I can't decide if its more important to test that the Onboarding works or more important to test when it shouldn't work.

2024-12-05 17:51 UTC, shayanaijaz approved these changes
LGTM. All tests pass other than the compress and extract apps which I'll take a look at

2024-12-16 19:41 UTC, merged