task/WMAQA-45  Shared Workspace Tests
TACC/Core-Portal-E2E pull request #23
Opened 2024-01-22 20:47 UTC by shayanaijaz

### Overview 

Added tests for shared workspaces. Also added a teardown project that deals with deleting shared workspaces directly using tapis 

### Changes 

- Added shared workspace tests which include adding, editing, and searching shared workspaces 
- Added a teardown project. This project runs at the end after all tests are ran. The shared workspace teardown authenticates with tapis using the test users authentication, gets the users shared workspace systems for the specific portal and deletes those systems 

### Testing 

- Run tests normally using npx playwright test and ensure all tests pass 
- As an addition, also try manually logging onto the portal the tests were ran on and ensure no shared workspaces exist

2024-09-09 22:52 UTC, shayanaijaz commented on tests/data-files/data-files-shared-workspace.spec.js
> +        await expect(page.locator('.modal-dialog')).not.toBeVisible();
Increased the timeouts for this test and also added retries. Should solve this issue now

2024-09-09 22:53 UTC, shayanaijaz commented on utils/pythonHelper.py
> +    "PORTAL_PROJECTS_SYSTEM_PREFIX": custom_portal_settings._PORTAL_PROJECTS_SYSTEM_PREFIX or ''
The or statements should work. Can you check what python version you have to make sure that isn't an issue?

2024-09-10 20:56 UTC, fnets requested changes
I think I have one change to make this more secure and another short research task for myself.

2024-09-10 20:56 UTC, fnets commented on tests/teardown/data-files-shared-workspaces.teardown.js
> +async function getAccessToken(page, username, password, tenant) {
It looks like this will work, but I think a more secure way to do it would be to use this api: 

https://github.com/TACC/Core-Portal/blob/4c210402098f09a7e03a5a739ae4dcf248ce46aa/server/portal/apps/auth/api/urls.py#L5

That way, we're not transmitting passwords or anything. Normally, I'd say we wouldn't want to use the portal to test the portal, but I think in this case it makes sense.

2024-09-10 20:56 UTC, fnets commented on tests/teardown/data-files-shared-workspaces.teardown.js
> +async function getSystems(page, tenant, projectPrefix, accessToken) {
Do we want to delete all the shared systems, or just the one we created in these tests? Is there an easy or free way to get that system id at system creation? I'll take a look to try and save you a headache.

2024-09-10 21:05 UTC, fnets commented on tests/teardown/data-files-shared-workspaces.teardown.js
> +async function getSystems(page, tenant, projectPrefix, accessToken) {
Oh, it looks like it's available in the Shared Workspaces view and in the URL.

2025-01-06 17:41 UTC, fnets approved these changes

2025-01-06 18:28 UTC, fnets approved these changes
In practice, it seems like the 'Edit Shared Workspace Name and Description' test is a little flaky, but I was able to get it to pass 3 times in a row.

2025-01-27 16:29 UTC, merged