Data Files fixtures.
TACC/Core-Portal-E2E pull request #24
Opened 2024-01-23 18:03 UTC by jmartinez-tacc

**Operations:**
- Upload file
- Create folder
- Delete resource (file/folder)
- Empty trash

**Usage:**
`import { test, expect } from '../../fixtures/fileOperationsFixture'`
Note: don't import `baseFixture`, it's properties are available on`fileOperationsFixture` since this class extends from `baseFixture`.

2024-01-24 22:18 UTC, fnets requested changes

2024-01-24 22:18 UTC, fnets commented on tests/data-files/data-files-add.spec.js
> +      expect (await page.getByRole('checkbox', { name: 'select file E2EtestFile1' }).isVisible());
The test is failing for me here, I think because the modal isn't being closed after the upload happens.
```suggestion
      await page.getByRole('dialog').getByLabel('Close').click();
      expect (await page.getByRole('checkbox', { name: 'select file E2EtestFile1' }).isVisible());
```

2024-01-25 15:00 UTC, fnets commented on tests/data-files/data-files-add.spec.js
> +      expect (await page.getByRole('checkbox', { name: 'select file E2EtestFile1' }).isVisible());
After running with the change, this expect is still failing because because it matches 9 selectors.

2024-01-25 15:29 UTC, fnets commented on tests/data-files/data-files-add.spec.js
> +      expect (await page.getByRole('checkbox', { name: 'select file E2EtestFile1' }).isVisible());
Reviewing this more, it seems like it was an issue with the Data FIles listing of the user. I'm marking this as resolved

2024-01-25 15:33 UTC, fnets requested changes
Could you add a teardown or cleanup function to run after these tests are run? The reason I ask is because if the delete test isn't run, then the test files are left in Data Files and it breaks any other times the tests that are run in the future. Otherwise, this works great!

2024-02-29 19:24 UTC, jmartinez-tacc commented
> Could you add a teardown or cleanup function to run after these tests are run? The reason I ask is because if the delete test isn't run, then the test files are left in Data Files and it breaks any other times the tests that are run in the future. Otherwise, this works great!

Done!

2024-02-29 19:24 UTC, closed without merging